### ISSUE TITLE
Lock-Logs informacion

### ISSUE THREAD

**Issue by DJanielFF** [StarDustCFW/Lock-Logs#9]
hola kronos que version me recomiendas de lock-logs la que has creado tu o la que ha forkeado erew70,ademas quiero saber si funciona en el ultimo firmware(18.1.0),quiero saber que riesgos conlleva al utilizarla y si podemos seguir utilzando los servicios en linea de nintendo por ejemplo en syscfw para hackear en linea y no ser baneado,un saludo

**Comment by Kronos2308** [comment]
La versión actual 1.1 funciona correctamente
